FROM kestra/kestra:v1.3@sha256:8f780985c391fb6d1627ef23fefb5fdf36865498e84b9718b3f34139259a7a1e

USER root

COPY --from=ghcr.io/astral-sh/uv:latest@sha256:90bbb3c16635e9627f49eec6539f956d70746c409209041800a0280b93152823 /uv /usr/local/bin/uv

COPY docker/kestra-entrypoint.sh /usr/local/bin/kestra-entrypoint.sh
RUN chmod +x /usr/local/bin/kestra-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/kestra-entrypoint.sh"]
